# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  test:
    desc: Test all
    cmds:
      - cmd: go test ./...

  cover:
    desc: Cover test
    cmds: 
      - cmd: go test -cover -coverprofile cover.out .

  profile:
    desc: Profile all
    cmds:
      - cmd: go test -cpuprofile cpu.prof -memprofile mem.prof -bench=. .
