# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test:
    cmds:
      - cmd: go test ./...

  cover:
    cmds: 
      - cmd: go test -cover -coverprofile cover.out ./...